name: Update images.json

on:
  push:
    paths:
      - "images/**" # Only trigger on changes in the images folder
  pull_request:
    paths:
      - "images/**" # Also trigger on changes in the images folder in PRs

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate images.json with durations
        run: |
          IMAGES_DIR="images"
          JSON_FILE="images.json"
          echo "[" > $JSON_FILE
          find "$IMAGES_DIR" -type f \( -name '*.jpg' -o -name '*.png' -o -name '*.jpeg' \) -print0 | \
          while IFS= read -r -d '' IMAGE; do
            # Extract filename and duration from image path
            filename=$(basename "$IMAGE")
            duration=$(echo "$filename" | grep -oE '^[0-9]+')
            if [ -z "$duration" ]; then
            duration="5000" # Default duration in milliseconds (5 seconds)
            echo "  { \"url\": \"$IMAGE\", \"duration\": $duration }," >> $JSON_FILE
          done
          # Remove the trailing comma from the last element
          sed -i '$ s/,$//' $JSON_FILE
          echo "]" >> $JSON_FILE

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add images.json
          git commit -m "Update images.json with durations"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
